spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fling}
    username: ${SPRING_DATASOURCE_USERNAME:fling}
    password: ${SPRING_DATASOURCE_PASSWORD:fling}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 25
        order_inserts: true
        order_updates: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    com.fling: INFO
